version: '3.8'

services:
  knowledge-companion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knowledge-companion
    ports:
      - "8010:8000"
    restart: unless-stopped
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
    env_file:
      - .env
    networks:
      - supabase_default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  supabase_default:
    external: true
