### Create contact (example - you'll need working `add_contact`)
POST http://localhost:8001/contacts
Content-Type: application/json

{
  "operation": "delete",
  "payload": {
    "contact_id": "93c95184-805f-4821-952e-7de6c6bad9b7"
  }
}