### Create a customer
POST http://localhost:8001/customers
Content-Type: application/json

{
  "name": "Acme Corp",
  "industry": "Tech",
  "size": "50-100",
  "region": "Europe",
  "status": "active",
  "mainpage_url": "https://testcorp.com",
  "aliases": [
    { "alias": "AC" },
    { "alias": "Acme" }
  ]
}